//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratoryMain
{
    using System;
    using System.Collections.Generic;
    
    public partial class actions
    {
        public int id { get; set; }
        public int id_service { get; set; }
        public int id_status { get; set; }
        public int id_order { get; set; }
        public string barcode { get; set; }
        public string result { get; set; }
    
        public virtual orders orders { get; set; }
        public virtual services services { get; set; }
        public virtual status_service status_service { get; set; }
    }
}
