//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratoryMain
{
    using System;
    using System.Collections.Generic;
    
    public partial class cheking_account
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int id_company { get; set; }
        public System.DateTime date { get; set; }
        public decimal sum { get; set; }
    
        public virtual policy_company policy_company { get; set; }
        public virtual users users { get; set; }
    }
}
