//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratoryMain
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_analizators
    {
        public int id { get; set; }
        public int id_analizator { get; set; }
        public int id_actions { get; set; }
        public System.DateTime date_of_receipt { get; set; }
        public string time { get; set; }
    
        public virtual analizators analizators { get; set; }
    }
}
