//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratoryMain
{
    using System;
    using System.Collections.Generic;
    
    public partial class history
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public System.DateTime lastenter { get; set; }
        public string ip_user { get; set; }
        public Nullable<System.DateTime> quit { get; set; }
    
        public virtual users users { get; set; }
    }
}
