//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratoryMain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class database : DbContext
    {
        public database()
            : base("name=database")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<action> actions { get; set; }
        public virtual DbSet<analizator> analizators { get; set; }
        public virtual DbSet<cheking_account> cheking_account { get; set; }
        public virtual DbSet<data_analizators> data_analizators { get; set; }
        public virtual DbSet<history> histories { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<policy_company> policy_company { get; set; }
        public virtual DbSet<policy_types> policy_types { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<service> services { get; set; }
        public virtual DbSet<status_service> status_service { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
